<?php

namespace Database\Seeders;

use Database\Seeders\Concerns\SeedsOnlyExistingColumns;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seed the ~50 canonical services across all 12 trades.
 *
 * Idempotent: uses updateOrInsertTable keyed on `code`.
 * Requires TradeSeeder to have run first (resolves trade IDs by slug).
 */
class ServiceCatalogSeeder extends Seeder
{
    use SeedsOnlyExistingColumns;

    public function run(): void
    {
        // Build a slug → id map for all trades.
        $tradeIds = DB::table('trades')->pluck('id', 'slug')->all();

        $services = $this->buildServices($tradeIds);

        foreach ($services as $service) {
            $this->updateOrInsertTable(
                'service_catalogs',
                ['code' => $service['code']],
                $service
            );
        }

        $this->command?->info('Service catalog initialized ('.count($services).' services).');
    }

    /** @param array<string, int> $tradeIds */
    private function buildServices(array $tradeIds): array
    {
        // Helper: resolve a trade id by slug (or fall back to nettoyage/cleaning).
        $tid = function (string $slug) use ($tradeIds): ?int {
            return $tradeIds[$slug]
                ?? $tradeIds['cleaning']
                ?? $tradeIds['nettoyage']
                ?? null;
        };

        return [
            // ── Nettoyage (CLN) ──────────────────────────────────────────────
            [
                'code' => 'NETTOYAGE_STANDARD',
                'name' => 'Nettoyage standard',
                'slug' => 'nettoyage-standard',
                'service_type' => 'nettoyage_standard',
                'description' => 'Prestation reguliere pour particuliers et petits bureaux.',
                'default_duration_minutes' => 120,
                'base_price' => 79,
                'sort_order' => 10,
                'trade_id' => $tid('cleaning'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'NETTOYAGE_PROFOND',
                'name' => 'Nettoyage profond',
                'slug' => 'nettoyage-profond',
                'service_type' => 'nettoyage_profond',
                'description' => 'Nettoyage approfondi ponctuel ou reprise complete.',
                'default_duration_minutes' => 180,
                'base_price' => 129,
                'sort_order' => 20,
                'trade_id' => $tid('cleaning'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'FIN_DE_CHANTIER',
                'name' => 'Fin de chantier',
                'slug' => 'fin-de-chantier',
                'service_type' => 'fin_de_chantier',
                'description' => 'Remise en etat apres travaux.',
                'default_duration_minutes' => 240,
                'base_price' => 189,
                'sort_order' => 30,
                'trade_id' => $tid('cleaning'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'requires_quote' => true,
                'requires_manual_validation' => true,
                'is_entreprise' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'FIN_DE_BAIL',
                'name' => 'Fin de bail',
                'slug' => 'fin-de-bail',
                'service_type' => 'fin_de_bail',
                'description' => 'Prestation de sortie avec controle renforce.',
                'default_duration_minutes' => 240,
                'base_price' => 179,
                'sort_order' => 40,
                'trade_id' => $tid('cleaning'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'BUREAUX',
                'name' => 'Nettoyage bureaux',
                'slug' => 'nettoyage-bureaux',
                'service_type' => 'bureaux',
                'description' => 'Nettoyage recurrent de bureaux et espaces corporate.',
                'default_duration_minutes' => 150,
                'base_price' => 149,
                'sort_order' => 50,
                'trade_id' => $tid('cleaning'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_entreprise' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => false,
                'currency' => 'EUR',
            ],
            [
                'code' => 'VITRES',
                'name' => 'Vitres et vitrines',
                'slug' => 'vitres-vitrines',
                'service_type' => 'vitres',
                'description' => 'Nettoyage des vitres, vitrines et surfaces vitrees.',
                'default_duration_minutes' => 90,
                'base_price' => 69,
                'sort_order' => 60,
                'trade_id' => $tid('cleaning'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],

            // ── Peinture (PNT) ───────────────────────────────────────────────
            [
                'code' => 'PEINTURE_INTERIEUR_MURS',
                'name' => 'Peinture interieur murs',
                'slug' => 'peinture-interieur-murs',
                'service_type' => 'peinture_murs',
                'description' => 'Peinture des murs interieurs, toutes pieces.',
                'default_duration_minutes' => 240,
                'base_price' => 15,
                'sort_order' => 10,
                'trade_id' => $tid('painting'),
                'billing_unit' => 'sqm',
                'vat_rate' => 6.00,
                'requires_site_visit' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'PEINTURE_PLAFOND',
                'name' => 'Peinture plafond',
                'slug' => 'peinture-plafond',
                'service_type' => 'peinture_plafond',
                'description' => 'Peinture des plafonds, preparation et finition.',
                'default_duration_minutes' => 180,
                'base_price' => 18,
                'sort_order' => 20,
                'trade_id' => $tid('painting'),
                'billing_unit' => 'sqm',
                'vat_rate' => 6.00,
                'requires_site_visit' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'PEINTURE_FACADE',
                'name' => 'Peinture facade exterieure',
                'slug' => 'peinture-facade-exterieure',
                'service_type' => 'peinture_facade',
                'description' => 'Ravalement et peinture de facade, echafaudage inclus.',
                'default_duration_minutes' => 480,
                'base_price' => 35,
                'sort_order' => 30,
                'trade_id' => $tid('painting'),
                'billing_unit' => 'sqm',
                'vat_rate' => 21.00,
                'requires_site_visit' => true,
                'requires_quote' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'PEINTURE_BOISERIES',
                'name' => 'Peinture boiseries',
                'slug' => 'peinture-boiseries',
                'service_type' => 'peinture_boiseries',
                'description' => 'Peinture et vernis des boiseries, portes, fenetres.',
                'default_duration_minutes' => 120,
                'base_price' => 60,
                'sort_order' => 40,
                'trade_id' => $tid('painting'),
                'billing_unit' => 'hour',
                'vat_rate' => 6.00,
                'requires_site_visit' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],

            // ── Batiment / Construction (BLD) ────────────────────────────────
            [
                'code' => 'BATIMENT_MACONNERIE',
                'name' => 'Maconnerie generale',
                'slug' => 'maconnerie-generale',
                'service_type' => 'maconnerie',
                'description' => 'Travaux de maconnerie, murs, cloisons, fondations.',
                'default_duration_minutes' => 480,
                'base_price' => 500,
                'sort_order' => 10,
                'trade_id' => $tid('construction'),
                'billing_unit' => 'flat',
                'vat_rate' => 6.00,
                'requires_site_visit' => true,
                'requires_quote' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'BATIMENT_ISOLATION',
                'name' => 'Isolation thermique',
                'slug' => 'isolation-thermique',
                'service_type' => 'isolation',
                'description' => 'Isolation des murs, combles et toitures.',
                'default_duration_minutes' => 480,
                'base_price' => 40,
                'sort_order' => 20,
                'trade_id' => $tid('construction'),
                'billing_unit' => 'sqm',
                'vat_rate' => 6.00,
                'requires_site_visit' => true,
                'requires_quote' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'BATIMENT_CARRELAGE',
                'name' => 'Carrelage et faience',
                'slug' => 'carrelage-faience',
                'service_type' => 'carrelage',
                'description' => 'Pose de carrelage sol et mur, faience cuisine et salle de bain.',
                'default_duration_minutes' => 360,
                'base_price' => 45,
                'sort_order' => 30,
                'trade_id' => $tid('construction'),
                'billing_unit' => 'sqm',
                'vat_rate' => 6.00,
                'requires_site_visit' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],

            // ── Plomberie (PLB) ──────────────────────────────────────────────
            [
                'code' => 'PLB_DEPANNAGE',
                'name' => 'Depannage plomberie',
                'slug' => 'depannage-plomberie',
                'service_type' => 'plomberie_depannage',
                'description' => 'Intervention urgente pour fuite, bouchon ou panne.',
                'default_duration_minutes' => 90,
                'base_price' => 89,
                'sort_order' => 10,
                'trade_id' => $tid('plumbing'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'PLB_INSTALLATION',
                'name' => 'Installation sanitaire',
                'slug' => 'installation-sanitaire',
                'service_type' => 'plomberie_installation',
                'description' => 'Pose lavabo, WC, douche, baignoire, robinetterie.',
                'default_duration_minutes' => 180,
                'base_price' => 75,
                'sort_order' => 20,
                'trade_id' => $tid('plumbing'),
                'billing_unit' => 'hour',
                'vat_rate' => 6.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'PLB_DEBOUCHAGE',
                'name' => 'Debouchage canalisation',
                'slug' => 'debouchage-canalisation',
                'service_type' => 'plomberie_debouchage',
                'description' => 'Debouchage evier, douche, WC, colonne.',
                'default_duration_minutes' => 60,
                'base_price' => 95,
                'sort_order' => 30,
                'trade_id' => $tid('plumbing'),
                'billing_unit' => 'flat',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'PLB_CHAUFFE_EAU',
                'name' => 'Remplacement chauffe-eau',
                'slug' => 'remplacement-chauffe-eau',
                'service_type' => 'plomberie_chauffe_eau',
                'description' => 'Depose ancien appareil, fourniture et pose nouveau chauffe-eau.',
                'default_duration_minutes' => 180,
                'base_price' => 350,
                'sort_order' => 40,
                'trade_id' => $tid('plumbing'),
                'billing_unit' => 'flat',
                'vat_rate' => 6.00,
                'requires_quote' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],

            // ── Electricite (ELC) ────────────────────────────────────────────
            [
                'code' => 'ELC_DEPANNAGE',
                'name' => 'Depannage electrique',
                'slug' => 'depannage-electrique',
                'service_type' => 'electricite_depannage',
                'description' => 'Panne de courant, court-circuit, disjoncteur.',
                'default_duration_minutes' => 60,
                'base_price' => 85,
                'sort_order' => 10,
                'trade_id' => $tid('electrical'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'ELC_TABLEAU',
                'name' => 'Installation tableau electrique',
                'slug' => 'installation-tableau-electrique',
                'service_type' => 'electricite_tableau',
                'description' => 'Remplacement ou installation tableau et disjoncteurs.',
                'default_duration_minutes' => 240,
                'base_price' => 450,
                'sort_order' => 20,
                'trade_id' => $tid('electrical'),
                'billing_unit' => 'flat',
                'vat_rate' => 6.00,
                'requires_quote' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'ELC_ECLAIRAGE',
                'name' => 'Installation eclairage',
                'slug' => 'installation-eclairage',
                'service_type' => 'electricite_eclairage',
                'description' => 'Pose spots, lustres, LED, eclairage exterieur.',
                'default_duration_minutes' => 120,
                'base_price' => 70,
                'sort_order' => 30,
                'trade_id' => $tid('electrical'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'ELC_CONFORMITE',
                'name' => 'Mise en conformite electrique',
                'slug' => 'mise-en-conformite-electrique',
                'service_type' => 'electricite_conformite',
                'description' => 'Audit et mise en conformite AREI, rapport inclus.',
                'default_duration_minutes' => 180,
                'base_price' => 280,
                'sort_order' => 40,
                'trade_id' => $tid('electrical'),
                'billing_unit' => 'flat',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],

            // ── Jardinage (GRD) ──────────────────────────────────────────────
            [
                'code' => 'GRD_TONTE',
                'name' => 'Tonte et desherbage',
                'slug' => 'tonte-desherbage',
                'service_type' => 'jardinage_tonte',
                'description' => 'Tonte de gazon, desherbage alles et massifs.',
                'default_duration_minutes' => 120,
                'base_price' => 55,
                'sort_order' => 10,
                'trade_id' => $tid('gardening'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'GRD_TAILLE',
                'name' => 'Taille haie et arbustes',
                'slug' => 'taille-haie-arbustes',
                'service_type' => 'jardinage_taille',
                'description' => 'Taille haies, arbustes et arbres fruitiers.',
                'default_duration_minutes' => 180,
                'base_price' => 65,
                'sort_order' => 20,
                'trade_id' => $tid('gardening'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'GRD_ELAGAGE',
                'name' => 'Elagage et abattage',
                'slug' => 'elagage-abattage',
                'service_type' => 'jardinage_elagage',
                'description' => 'Elagage grands arbres, abattage, evacuation bois.',
                'default_duration_minutes' => 360,
                'base_price' => 150,
                'sort_order' => 30,
                'trade_id' => $tid('gardening'),
                'billing_unit' => 'flat',
                'vat_rate' => 21.00,
                'requires_quote' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'GRD_ENTRETIEN',
                'name' => 'Entretien complet jardin',
                'slug' => 'entretien-complet-jardin',
                'service_type' => 'jardinage_entretien',
                'description' => 'Entretien complet : tonte, taille, desherbage, ramassage.',
                'default_duration_minutes' => 240,
                'base_price' => 90,
                'sort_order' => 40,
                'trade_id' => $tid('gardening'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],

            // ── Demenagement (MOV) ───────────────────────────────────────────
            [
                'code' => 'MOV_APPARTEMENT',
                'name' => 'Demenagement appartement',
                'slug' => 'demenagement-appartement',
                'service_type' => 'demenagement_appartement',
                'description' => 'Demenagement complet appartement T1 a T4.',
                'default_duration_minutes' => 480,
                'base_price' => 450,
                'sort_order' => 10,
                'trade_id' => $tid('moving'),
                'billing_unit' => 'flat',
                'vat_rate' => 21.00,
                'requires_site_visit' => true,
                'requires_quote' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'MOV_MAISON',
                'name' => 'Demenagement maison',
                'slug' => 'demenagement-maison',
                'service_type' => 'demenagement_maison',
                'description' => 'Demenagement maison avec monte-meuble si necessaire.',
                'default_duration_minutes' => 720,
                'base_price' => 900,
                'sort_order' => 20,
                'trade_id' => $tid('moving'),
                'billing_unit' => 'flat',
                'vat_rate' => 21.00,
                'requires_site_visit' => true,
                'requires_quote' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'MOV_BUREAUX',
                'name' => 'Demenagement bureaux',
                'slug' => 'demenagement-bureaux',
                'service_type' => 'demenagement_bureaux',
                'description' => 'Demenagement entreprise, materiel IT et mobilier.',
                'default_duration_minutes' => 960,
                'base_price' => 1500,
                'sort_order' => 30,
                'trade_id' => $tid('moving'),
                'billing_unit' => 'flat',
                'vat_rate' => 21.00,
                'requires_site_visit' => true,
                'requires_quote' => true,
                'is_entreprise' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => false,
                'currency' => 'EUR',
            ],

            // ── Garde d'enfants (CHD) ────────────────────────────────────────
            [
                'code' => 'CHD_PONCTUEL',
                'name' => 'Babysitting ponctuel',
                'slug' => 'babysitting-ponctuel',
                'service_type' => 'garde_ponctuelle',
                'description' => 'Garde ponctuelle a domicile, soir ou week-end.',
                'default_duration_minutes' => 180,
                'base_price' => 14,
                'sort_order' => 10,
                'trade_id' => $tid('childcare'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => false,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'CHD_REGULIER',
                'name' => 'Garde reguliere',
                'slug' => 'garde-reguliere-enfants',
                'service_type' => 'garde_reguliere',
                'description' => 'Garde hebdomadaire ou mensuelle, planning fixe.',
                'default_duration_minutes' => 240,
                'base_price' => 12,
                'sort_order' => 20,
                'trade_id' => $tid('childcare'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => false,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'CHD_DEVOIRS',
                'name' => 'Aide aux devoirs',
                'slug' => 'aide-aux-devoirs',
                'service_type' => 'aide_devoirs',
                'description' => 'Suivi scolaire et aide aux devoirs a domicile.',
                'default_duration_minutes' => 90,
                'base_price' => 20,
                'sort_order' => 30,
                'trade_id' => $tid('childcare'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => false,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],

            // ── Toiture (ROF) ────────────────────────────────────────────────
            [
                'code' => 'ROF_REPARATION',
                'name' => 'Reparation toiture',
                'slug' => 'reparation-toiture',
                'service_type' => 'toiture_reparation',
                'description' => 'Remplacement tuiles cassees, solin, faitiere.',
                'default_duration_minutes' => 240,
                'base_price' => 25,
                'sort_order' => 10,
                'trade_id' => $tid('roofing'),
                'billing_unit' => 'sqm',
                'vat_rate' => 6.00,
                'requires_site_visit' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'ROF_ETANCHEITE',
                'name' => 'Etancheite toiture plate',
                'slug' => 'etancheite-toiture-plate',
                'service_type' => 'toiture_etancheite',
                'description' => 'Membrane EPDM ou bitume pour toiture plate.',
                'default_duration_minutes' => 480,
                'base_price' => 45,
                'sort_order' => 20,
                'trade_id' => $tid('roofing'),
                'billing_unit' => 'sqm',
                'vat_rate' => 6.00,
                'requires_site_visit' => true,
                'requires_quote' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'ROF_NETTOYAGE',
                'name' => 'Nettoyage toiture',
                'slug' => 'nettoyage-toiture',
                'service_type' => 'toiture_nettoyage',
                'description' => 'Demoussage, nettoyage haute pression et traitement.',
                'default_duration_minutes' => 300,
                'base_price' => 8,
                'sort_order' => 30,
                'trade_id' => $tid('roofing'),
                'billing_unit' => 'sqm',
                'vat_rate' => 21.00,
                'requires_site_visit' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],

            // ── Levage / Lift (LFT) ──────────────────────────────────────────
            [
                'code' => 'LFT_NACELLE',
                'name' => 'Location nacelle avec operateur',
                'slug' => 'location-nacelle-operateur',
                'service_type' => 'levage_nacelle',
                'description' => 'Nacelle elevatrice avec operateur certifie CACES.',
                'default_duration_minutes' => 480,
                'base_price' => 380,
                'sort_order' => 10,
                'trade_id' => $tid('lifting'),
                'billing_unit' => 'flat',
                'vat_rate' => 21.00,
                'requires_site_visit' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => false,
                'currency' => 'EUR',
            ],
            [
                'code' => 'LFT_MONTE_CHARGE',
                'name' => 'Monte-charge facade',
                'slug' => 'monte-charge-facade',
                'service_type' => 'levage_monte_charge',
                'description' => 'Installation monte-charge pour demenagement en hauteur.',
                'default_duration_minutes' => 240,
                'base_price' => 250,
                'sort_order' => 20,
                'trade_id' => $tid('lifting'),
                'billing_unit' => 'flat',
                'vat_rate' => 21.00,
                'requires_site_visit' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'LFT_GRUE',
                'name' => 'Grue mobile avec grutier',
                'slug' => 'grue-mobile-grutier',
                'service_type' => 'levage_grue',
                'description' => 'Grue automotrice pour chantiers lourds, grutier certifie.',
                'default_duration_minutes' => 480,
                'base_price' => 900,
                'sort_order' => 30,
                'trade_id' => $tid('lifting'),
                'billing_unit' => 'flat',
                'vat_rate' => 21.00,
                'requires_site_visit' => true,
                'requires_quote' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => false,
                'currency' => 'EUR',
            ],

            // ── Renovation (RNV) ─────────────────────────────────────────────
            [
                'code' => 'RNV_CUISINE',
                'name' => 'Renovation cuisine',
                'slug' => 'renovation-cuisine',
                'service_type' => 'renovation_cuisine',
                'description' => 'Renovation complete cuisine : sol, carrelage, peinture, plomberie.',
                'default_duration_minutes' => 960,
                'base_price' => 80,
                'sort_order' => 10,
                'trade_id' => $tid('renovation'),
                'billing_unit' => 'sqm',
                'vat_rate' => 6.00,
                'requires_site_visit' => true,
                'requires_quote' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'RNV_SDB',
                'name' => 'Renovation salle de bain',
                'slug' => 'renovation-salle-de-bain',
                'service_type' => 'renovation_sdb',
                'description' => 'Renovation salle de bain : faience, sanitaires, douche.',
                'default_duration_minutes' => 960,
                'base_price' => 90,
                'sort_order' => 20,
                'trade_id' => $tid('renovation'),
                'billing_unit' => 'sqm',
                'vat_rate' => 6.00,
                'requires_site_visit' => true,
                'requires_quote' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'RNV_SOL',
                'name' => 'Pose revetement sol',
                'slug' => 'pose-revetement-sol',
                'service_type' => 'renovation_sol',
                'description' => 'Pose parquet, carrelage, stratifie, vinyl.',
                'default_duration_minutes' => 360,
                'base_price' => 35,
                'sort_order' => 30,
                'trade_id' => $tid('renovation'),
                'billing_unit' => 'sqm',
                'vat_rate' => 6.00,
                'requires_site_visit' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'RNV_COMPLETE',
                'name' => 'Renovation complete',
                'slug' => 'renovation-complete',
                'service_type' => 'renovation_complete',
                'description' => 'Renovation integrale : tous corps de metier coordonnes.',
                'default_duration_minutes' => 2880,
                'base_price' => 120,
                'sort_order' => 40,
                'trade_id' => $tid('renovation'),
                'billing_unit' => 'sqm',
                'vat_rate' => 6.00,
                'requires_site_visit' => true,
                'requires_quote' => true,
                'requires_manual_validation' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],

            // ── Securite / Gardiennage (SEC) ─────────────────────────────────
            [
                'code' => 'SEC_GARDIENNAGE',
                'name' => 'Gardiennage de site',
                'slug' => 'gardiennage-de-site',
                'service_type' => 'securite_gardiennage',
                'description' => 'Agent de securite pour surveillance de site 24h/24.',
                'default_duration_minutes' => 480,
                'base_price' => 22,
                'sort_order' => 10,
                'trade_id' => $tid('security'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_entreprise' => true,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => false,
                'currency' => 'EUR',
            ],
            [
                'code' => 'SEC_EVENEMENT',
                'name' => 'Securite evenementielle',
                'slug' => 'securite-evenementielle',
                'service_type' => 'securite_evenement',
                'description' => 'Agents pour concerts, evenements, mariages, expos.',
                'default_duration_minutes' => 480,
                'base_price' => 25,
                'sort_order' => 20,
                'trade_id' => $tid('security'),
                'billing_unit' => 'hour',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => true,
                'currency' => 'EUR',
            ],
            [
                'code' => 'SEC_RONDES',
                'name' => 'Rondes de surveillance',
                'slug' => 'rondes-de-surveillance',
                'service_type' => 'securite_rondes',
                'description' => 'Rondes nocturnes ou periodes de fermeture.',
                'default_duration_minutes' => 60,
                'base_price' => 60,
                'sort_order' => 30,
                'trade_id' => $tid('security'),
                'billing_unit' => 'flat',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => false,
                'currency' => 'EUR',
            ],
            [
                'code' => 'SEC_INTERVENTION',
                'name' => 'Agent d\'intervention',
                'slug' => 'agent-intervention',
                'service_type' => 'securite_intervention',
                'description' => 'Intervention rapide sur alarme ou incident.',
                'default_duration_minutes' => 30,
                'base_price' => 95,
                'sort_order' => 40,
                'trade_id' => $tid('security'),
                'billing_unit' => 'flat',
                'vat_rate' => 21.00,
                'is_active' => true,
                'is_b2b_available' => true,
                'is_personal_available' => false,
                'currency' => 'EUR',
            ],
        ];
    }
}
