<div class="space-y-8">
    <div>
        <h1 class="text-2xl font-bold text-slate-900">Mon équipe terrain</h1>
        <p class="mt-1 text-sm text-slate-600">Vision chef d’équipe / membre d’équipe pour les missions groupées et les comptes professionnels.</p>
    </div>
    <div class="grid gap-6 xl:grid-cols-2">
        <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
            <div class="flex items-center justify-between"><h2 class="text-lg font-bold text-slate-900">Équipes que je pilote</h2><span class="rounded-full bg-blue-100 px-3 py-1 text-xs font-semibold text-blue-700"><?php echo e($ledTeams->count()); ?></span></div>
            <div class="mt-4 space-y-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $ledTeams; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $team): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="rounded-2xl border border-slate-200 p-4"><div class="flex items-center justify-between gap-4"><div><p class="font-semibold text-slate-900"><?php echo e($team->name); ?></p><p class="text-xs text-slate-500 mt-1"><?php echo e($team->serviceZone->name ?? 'Zone non définie'); ?> · <?php echo e($team->organizationAccount->name ?? 'Compte générique'); ?></p></div><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700">Lead</span></div><div class="mt-3 flex flex-wrap gap-2 text-xs text-slate-600"><span class="rounded-full bg-slate-100 px-3 py-1"><?php echo e($team->activeMembers->count()); ?> membre(s)</span><span class="rounded-full bg-slate-100 px-3 py-1">Capacité <?php echo e($team->max_concurrent_missions ?? '—'); ?></span><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($team->servicePartner): ?><span class="rounded-full bg-amber-100 px-3 py-1 text-amber-700">Partenaire <?php echo e($team->servicePartner->name); ?></span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-sm text-slate-500">Tu n’es encore lead d’aucune équipe terrain.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
        </section>
        <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
            <div class="flex items-center justify-between"><h2 class="text-lg font-bold text-slate-900">Équipes où je suis membre</h2><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700"><?php echo e($memberTeams->count()); ?></span></div>
            <div class="mt-4 space-y-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $memberTeams; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $team): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="rounded-2xl border border-slate-200 p-4"><p class="font-semibold text-slate-900"><?php echo e($team->name); ?></p><p class="text-xs text-slate-500 mt-1">Lead : <?php echo e($team->teamLead->name ?? 'Non défini'); ?> · <?php echo e($team->serviceZone->name ?? 'Zone non définie'); ?></p></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-sm text-slate-500">Tu n’es membre d’aucune équipe terrain active.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
        </section>
    </div>
    <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm">
        <div class="flex items-center justify-between"><h2 class="text-lg font-bold text-slate-900">Missions d’équipe actives</h2><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700"><?php echo e($activeTeamAssignments->count()); ?></span></div>
        <div class="mt-4 space-y-3"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $activeTeamAssignments; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $assignment): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="rounded-2xl border border-slate-200 p-4"><div class="flex items-center justify-between gap-3"><div><p class="font-semibold text-slate-900"><?php echo e($assignment->fieldTeam->name); ?></p><p class="text-xs text-slate-500 mt-1">Mission #<?php echo e($assignment->mission_id); ?> · <?php echo e($assignment->mission->organizationAccount->name ?? 'Compte standard'); ?></p></div><span class="rounded-full bg-blue-100 px-3 py-1 text-xs font-semibold text-blue-700"><?php echo e(strtoupper($assignment->assignment_status)); ?></span></div><div class="mt-3 text-sm text-slate-600 space-y-1"><p>Client : <?php echo e($assignment->mission->rendezVous->client->name ?? '—'); ?></p><p>Site : <?php echo e($assignment->mission->organizationSite->name ?? $assignment->mission->rendezVous->location_display); ?></p><p>Planifié : <?php echo e(optional($assignment->mission->planned_start_at)->format('d/m/Y H:i') ?? '—'); ?></p></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-sm text-slate-500">Aucune mission d’équipe active pour le moment.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
    </section>
</div>
<?php /**PATH C:\Users\mmdar\Desktop\code\work\CleanUx\resources\views/livewire/employe/equipe-terrain.blade.php ENDPATH**/ ?>