<div class="space-y-8">
    <div class="flex items-center justify-between gap-4">
        <div>
            <h1 class="text-2xl font-bold text-slate-900">Équipes terrain & partenaires</h1>
            <p class="text-sm text-slate-600 mt-1">Fondations opérationnelles pour équipes internes, leads et partenaires d’exécution.</p>
        </div>
        <div class="flex gap-2">
            <button wire:click="newTeam" class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Nouvelle équipe</button>
            <button wire:click="newPartner" class="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700">Nouveau partenaire</button>
        </div>
    </div>
    <div class="grid gap-6 xl:grid-cols-2">
        <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm space-y-5">
            <div class="flex items-center justify-between"><h2 class="text-lg font-bold text-slate-900">Équipes terrain</h2><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600"><?php echo e($teams->count()); ?> équipe(s)</span></div>
            <div class="grid gap-3 lg:grid-cols-2"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $teams; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $team): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><button wire:click="selectTeam(<?php echo e($team->id); ?>)" class="rounded-2xl border p-4 text-left transition <?php echo e($selectedTeam && $selectedTeam->id === $team->id ? 'border-blue-500 bg-blue-50' : 'border-slate-200 bg-slate-50 hover:bg-white'); ?>"><div class="flex items-center justify-between gap-3"><div><p class="font-semibold text-slate-900"><?php echo e($team->name); ?></p><p class="text-xs text-slate-500 mt-1"><?php echo e($team->serviceZone->name ?? 'Zone non définie'); ?></p></div><span class="rounded-full px-2 py-1 text-[11px] font-semibold <?php echo e($team->status === 'active' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'); ?>"><?php echo e(strtoupper($team->status)); ?></span></div><div class="mt-3 text-xs text-slate-600 space-y-1"><p>Lead : <?php echo e($team->teamLead->name ?? 'Non défini'); ?></p><p>Compte : <?php echo e($team->organizationAccount->name ?? 'Générique'); ?></p><p><?php echo e($team->is_internal ? 'Interne' : 'Partenaire'); ?> <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($team->servicePartner): ?> · <?php echo e($team->servicePartner->name); ?> <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></p></div></button><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
            <div class="rounded-2xl border border-slate-200 p-4 space-y-4">
                <h3 class="font-semibold text-slate-900"><?php echo e($selectedTeam ? 'Modifier l’équipe' : 'Créer une équipe'); ?></h3>
                <div class="grid gap-4 md:grid-cols-2">
                    <div><label class="text-sm font-medium text-slate-700">Nom</label><input wire:model.defer="teamForm.name" type="text" class="mt-1 w-full rounded-xl border-slate-300" /></div>
                    <div><label class="text-sm font-medium text-slate-700">Pays</label><select wire:model.defer="teamForm.country_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">—</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $countries; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $country): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($country->id); ?>"><?php echo e($country->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
                    <div><label class="text-sm font-medium text-slate-700">Zone</label><select wire:model.defer="teamForm.service_zone_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">—</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $zones; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $zone): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($zone->id); ?>"><?php echo e($zone->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
                    <div><label class="text-sm font-medium text-slate-700">Compte entreprise</label><select wire:model.defer="teamForm.organization_account_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">—</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $accounts; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $account): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($account->id); ?>"><?php echo e($account->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
                    <div><label class="text-sm font-medium text-slate-700">Partenaire</label><select wire:model.defer="teamForm.service_partner_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">—</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $partners; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $partner): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($partner->id); ?>"><?php echo e($partner->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
                    <div><label class="text-sm font-medium text-slate-700">Chef d’équipe</label><select wire:model.defer="teamForm.team_lead_user_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">—</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $employees; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $employee): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($employee->id); ?>"><?php echo e($employee->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
                    <div><label class="text-sm font-medium text-slate-700">Statut</label><select wire:model.defer="teamForm.status" class="mt-1 w-full rounded-xl border-slate-300"><option value="active">Active</option><option value="pilot">Pilot</option><option value="inactive">Inactive</option></select></div>
                    <div><label class="text-sm font-medium text-slate-700">Capacité max missions simultanées</label><input wire:model.defer="teamForm.max_concurrent_missions" type="number" min="1" class="mt-1 w-full rounded-xl border-slate-300" /></div>
                </div>
                <div class="flex items-center gap-2"><input wire:model.defer="teamForm.is_internal" id="team-internal" type="checkbox" class="rounded border-slate-300" /><label for="team-internal" class="text-sm text-slate-700">Équipe interne</label></div>
                <div><label class="text-sm font-medium text-slate-700">Notes</label><textarea wire:model.defer="teamForm.notes" rows="3" class="mt-1 w-full rounded-xl border-slate-300"></textarea></div>
                <button wire:click="saveTeam" class="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Enregistrer l’équipe</button>
            </div>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($selectedTeam): ?>
            <div class="rounded-2xl border border-slate-200 p-4 space-y-4">
                <div class="flex items-center justify-between"><h3 class="font-semibold text-slate-900">Membres de <?php echo e($selectedTeam->name); ?></h3><span class="text-xs text-slate-500"><?php echo e($selectedTeam->activeMembers->count()); ?> actif(s)</span></div>
                <div class="grid gap-3 md:grid-cols-3"><div><label class="text-sm font-medium text-slate-700">Employé</label><select wire:model.defer="memberForm.user_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">—</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $employees; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $employee): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($employee->id); ?>"><?php echo e($employee->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div><div><label class="text-sm font-medium text-slate-700">Rôle</label><select wire:model.defer="memberForm.role_on_team" class="mt-1 w-full rounded-xl border-slate-300"><option value="team_lead">Chef d’équipe</option><option value="senior_agent">Senior agent</option><option value="agent">Agent</option><option value="specialist">Spécialiste</option><option value="driver">Chauffeur</option></select></div><div class="flex items-end gap-3"><label class="inline-flex items-center gap-2 text-sm text-slate-700"><input wire:model.defer="memberForm.is_team_lead" type="checkbox" class="rounded border-slate-300" />Lead</label><button wire:click="addMember" class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Ajouter</button></div></div>
                <div class="space-y-2"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $selectedTeam->activeMembers; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $member): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3 text-sm"><div><p class="font-medium text-slate-900"><?php echo e($member->user->name); ?></p><p class="text-slate-500"><?php echo e($member->role_on_team); ?></p></div><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($member->is_team_lead): ?><span class="rounded-full bg-blue-100 px-3 py-1 text-xs font-semibold text-blue-700">Lead</span><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-sm text-slate-500">Aucun membre actif pour cette équipe.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
            </div>
            <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        </section>
        <section class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm space-y-5">
            <div class="flex items-center justify-between"><h2 class="text-lg font-bold text-slate-900">Partenaires d’exécution</h2><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600"><?php echo e($partners->count()); ?> partenaire(s)</span></div>
            <div class="grid gap-3 lg:grid-cols-2"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $partners; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $partner): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><button wire:click="selectPartner(<?php echo e($partner->id); ?>)" class="rounded-2xl border p-4 text-left transition <?php echo e($selectedPartner && $selectedPartner->id === $partner->id ? 'border-blue-500 bg-blue-50' : 'border-slate-200 bg-slate-50 hover:bg-white'); ?>"><div class="flex items-center justify-between gap-3"><div><p class="font-semibold text-slate-900"><?php echo e($partner->name); ?></p><p class="text-xs text-slate-500 mt-1"><?php echo e($partner->country->name ?? 'Pays non défini'); ?></p></div><span class="rounded-full px-2 py-1 text-[11px] font-semibold <?php echo e($partner->is_active ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-200 text-slate-600'); ?>"><?php echo e($partner->is_active ? 'ACTIF' : 'OFF'); ?></span></div><div class="mt-3 text-xs text-slate-600 space-y-1"><p><?php echo e($partner->email ?: 'Email non défini'); ?></p><p>Qualité : <?php echo e($partner->quality_score ?? '—'); ?></p></div></button><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
            <div class="rounded-2xl border border-slate-200 p-4 space-y-4">
                <h3 class="font-semibold text-slate-900"><?php echo e($selectedPartner ? 'Modifier le partenaire' : 'Créer un partenaire'); ?></h3>
                <div class="grid gap-4 md:grid-cols-2">
                    <div><label class="text-sm font-medium text-slate-700">Nom</label><input wire:model.defer="partnerForm.name" type="text" class="mt-1 w-full rounded-xl border-slate-300" /></div>
                    <div><label class="text-sm font-medium text-slate-700">Raison sociale</label><input wire:model.defer="partnerForm.legal_name" type="text" class="mt-1 w-full rounded-xl border-slate-300" /></div>
                    <div><label class="text-sm font-medium text-slate-700">Pays</label><select wire:model.defer="partnerForm.country_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">—</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $countries; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $country): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($country->id); ?>"><?php echo e($country->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div>
                    <div><label class="text-sm font-medium text-slate-700">Statut</label><select wire:model.defer="partnerForm.status" class="mt-1 w-full rounded-xl border-slate-300"><option value="active">Active</option><option value="pilot">Pilot</option><option value="inactive">Inactive</option></select></div>
                    <div><label class="text-sm font-medium text-slate-700">Email</label><input wire:model.defer="partnerForm.email" type="email" class="mt-1 w-full rounded-xl border-slate-300" /></div>
                    <div><label class="text-sm font-medium text-slate-700">Téléphone</label><input wire:model.defer="partnerForm.phone" type="text" class="mt-1 w-full rounded-xl border-slate-300" /></div>
                    <div><label class="text-sm font-medium text-slate-700">Email facturation</label><input wire:model.defer="partnerForm.billing_email" type="email" class="mt-1 w-full rounded-xl border-slate-300" /></div>
                    <div><label class="text-sm font-medium text-slate-700">Score qualité</label><input wire:model.defer="partnerForm.quality_score" type="number" step="0.01" min="0" max="100" class="mt-1 w-full rounded-xl border-slate-300" /></div>
                </div>
                <div class="flex items-center gap-2"><input wire:model.defer="partnerForm.is_active" id="partner-active" type="checkbox" class="rounded border-slate-300" /><label for="partner-active" class="text-sm text-slate-700">Partenaire actif</label></div>
                <div><label class="text-sm font-medium text-slate-700">Notes</label><textarea wire:model.defer="partnerForm.notes" rows="3" class="mt-1 w-full rounded-xl border-slate-300"></textarea></div>
                <button wire:click="savePartner" class="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white">Enregistrer le partenaire</button>
            </div>
            <?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php if($selectedPartner): ?>
            <div class="rounded-2xl border border-slate-200 p-4 space-y-4">
                <div class="flex items-center justify-between"><h3 class="font-semibold text-slate-900">Couvertures & capacités</h3><span class="text-xs text-slate-500"><?php echo e($selectedPartner->zoneCoverages->count()); ?> couverture(s)</span></div>
                <div class="grid gap-3 md:grid-cols-4"><div><label class="text-sm font-medium text-slate-700">Zone</label><select wire:model.defer="coverageForm.service_zone_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">—</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $zones; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $zone): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($zone->id); ?>"><?php echo e($zone->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div><div><label class="text-sm font-medium text-slate-700">Service</label><select wire:model.defer="coverageForm.service_catalog_id" class="mt-1 w-full rounded-xl border-slate-300"><option value="">Tous</option><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__currentLoopData = $services; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $service): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><option value="<?php echo e($service->id); ?>"><?php echo e($service->name); ?></option><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></select></div><div><label class="text-sm font-medium text-slate-700">Capacité / jour</label><input wire:model.defer="coverageForm.max_daily_capacity" type="number" min="1" class="mt-1 w-full rounded-xl border-slate-300" /></div><div><label class="text-sm font-medium text-slate-700">SLA réponse (h)</label><input wire:model.defer="coverageForm.sla_response_hours" type="number" min="1" class="mt-1 w-full rounded-xl border-slate-300" /></div></div>
                <div class="flex items-center justify-between"><div class="w-32"><label class="text-sm font-medium text-slate-700">Priorité</label><input wire:model.defer="coverageForm.priority" type="number" min="1" max="100" class="mt-1 w-full rounded-xl border-slate-300" /></div><button wire:click="addCoverage" class="rounded-xl bg-slate-900 px-4 py-2 text-sm font-semibold text-white">Ajouter la couverture</button></div>
                <div class="space-y-2"><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if BLOCK]><![endif]--><?php endif; ?><?php $__empty_1 = true; $__currentLoopData = $selectedPartner->zoneCoverages; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $coverage): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><div class="rounded-xl bg-slate-50 px-4 py-3 text-sm text-slate-700"><div class="font-medium text-slate-900"><?php echo e($coverage->serviceZone->name ?? 'Zone'); ?></div><div class="mt-1 text-xs text-slate-500">Service : <?php echo e($coverage->serviceCatalog->name ?? 'Tous'); ?> · Priorité <?php echo e($coverage->priority); ?> · Capacité <?php echo e($coverage->max_daily_capacity ?? '—'); ?> · SLA <?php echo e($coverage->sla_response_hours ?? '—'); ?>h</div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><p class="text-sm text-slate-500">Aucune couverture configurée pour ce partenaire.</p><?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?></div>
            </div>
            <?php endif; ?><?php if(\Livewire\Mechanisms\ExtendBlade\ExtendBlade::isRenderingLivewireComponent()): ?><!--[if ENDBLOCK]><![endif]--><?php endif; ?>
        </section>
    </div>
</div>
<?php /**PATH C:\Users\mmdar\Desktop\code\work\CleanUx\resources\views/livewire/admin/gestion-equipes-partenaires.blade.php ENDPATH**/ ?>